apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.trainingServiceLabel }}
  template:
    metadata:
      labels:
        component: {{ .Values.trainingServiceLabel }}
    spec:
      containers:
        - name: training-service
          image: ariya23156/sfmlops-training-service
          ports:
            - containerPort: {{ .Values.trainingServicePort }}
          envFrom:
            - configMapRef:
                name: global-configmap
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:{{ .Values.mlflowPort }}"
            - name: DB_CONNECTION_URL
              value: "postgresql://spark_user:SuperSecurePwdHere@postgres:{{ .Values.postgresPort }}/spark_pg_db"
---

apiVersion: v1
kind: Service
metadata:
  name: training-service-service
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.trainingServiceLabel }}
  ports:
    - port: {{ .Values.trainingServicePort }}
      targetPort: {{ .Values.trainingServicePort }}
