containerBaseImage:
  dataProducer:
  trainingService:
  forecastService:
  mlflow:
  ray:
  webUi:


kafkaReleaseName: kafka-release
kafkaNamespace: kafka

webUiPort: 8000
webUiLabel: web-ui

trainingServiceLabel: training-service
trainingServicePort: 4243

forecastServiceLabel: forecast-service
forecastServicePort: 4242

mlflowPort: 5050
mlflowLabel: mlflow
mlflowPvcName: mlflow-pvc
mlflowArtifactRoot: /storage/mlruns/

postgresPort: 5432
postgresLabel: postgres
postgresPvcName: postgres-pvc
postgresInitConfigMapName: postgres-init-configmap

pgadminPort: 16543
pgadminLabel: pgadmin
pgadminPvcName: pgadmin-pvc

kafkaUiPort: 8800
kafkaUiLabel: kafka-ui

dataProducerLabel: data-producer

# This is also hardcoded in `values-airflow.yaml`
sparkStreamingPvcName: spark-streaming-pvc
