apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.forecastServiceLabel }}
  template:
    metadata:
      labels:
        component: {{ .Values.forecastServiceLabel }}
    spec:
      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: {{ .Values.mlflowPvcName }}
      containers:
        - name: forecast-service
          image: {{ .Values.containerMainImage.forecastService }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.forecastServicePort }}
          volumeMounts:
            - name: mlflow-data
              mountPath: {{ .Values.mlflowArtifactRoot }}
          envFrom:
            - configMapRef:
                name: global-configmap
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow-service:{{ .Values.mlflowPort }}"
---

apiVersion: v1
kind: Service
metadata:
  name: forecast-service-service
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.forecastServiceLabel }}
  ports:
    - port: {{ .Values.forecastServicePort }}
      targetPort: {{ .Values.forecastServicePort }}
