apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /$(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: web-ui-service
                port:
                  number: 80
          - path: /api/trainers/$(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: training-service-service
                port:
                  number: {{ .Values.trainingServicePort }}
